server:
  port: 8082
  servlet:
    context-path: /api-v1

spring:
  application:
    name: credit-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditdb
      auto-index-creation: true
